repos:
  -   repo: local
      hooks:
      -   id: pylint
          name: pylint
          entry: pylint
          language: system
          types: [python]
          args:
            [
              "-rn", # Only display messages
              "-sn", # Don't display the score
              "--rcfile=H:/Users/basto/Documents/Basico do basico/clean-architecture/.pylintrc",
              "--load-plugins=pylint.extensions.docparams", # Load the extension
            ]
      -   id: requirements
          name: requirements
          entry: bash -c 'source clean-architecture/virtual-env/bin/activate; pip freeze > clean-architecture/requirements.txt; git add clean-architecture/requirements.txt'
          language: system
          pass_filenames: false
          stages: [commit]